// Code generated by "json-ice --type=Location"; DO NOT EDIT.

package sdk

import "github.com/moznion/go-json-ice/serializer"

func MarshalLocationAsJSON(s *Location) ([]byte, error) {
	buff := make([]byte, 1, 54)
	buff[0] = '{'
	buff = append(buff, "\"lat\":"...)
	buff = serializer.AppendSerializedFloat(buff, float64(s.Lat))
	buff = append(buff, ',')
	buff = append(buff, "\"lon\":"...)
	buff = serializer.AppendSerializedFloat(buff, float64(s.Lon))
	buff = append(buff, ',')
	if buff[len(buff)-1] == ',' {
		buff[len(buff)-1] = '}'
	} else {
		buff = append(buff, '}')
	}
	return buff, nil
}
